baseurl = "https://michalkowol.github.io/"
title = "Michał Kowol | Tech Blog"
languageCode = "en-us"

theme = "lanyon-hugo"

[params]
  author = "Michał Kowol"
  DateForm = "2006-01-02"
  sidebar = "Michał Kowol"
  description = "Tech Blog"
  themeColor = "theme-base-0d"
  disqusShortname = "michalkowol"

[[menu.main]]
  name = "Blog"
  url = "/posts"

[[menu.main]]
  name = "Development"
  url = "/categories/development"

[[menu.main]]
  name = "GitHub Projects"
  url = "https://github.com/michalkowol"