baseurl = "https://michalkowol.github.io/"
title = "Michał Kowol | Tech Blog"
languageCode = "en-us"

theme = "hyde"

[params]
	author = "Michał Kowol"
  sidebar = "Michał Kowol"
  description = "Tech Blog"
	themeColor = "theme-base-0d"
  disqusShortname = "michalkowol"

[[menu.main]]
  name = "Blog"
  url = "/posts"

[[menu.main]]
  name = "Development"
  url = "/categories/development"

[[menu.social]]
  pre = "<i class='fa fa-twitter'></i>"
  url = "http://www.twitter.com/michalkowol"
  identifier = "twitter"