baseurl = "https://michalkowol.github.io/"
languageCode = "en-us"

theme = "lanyon-hugo"

builddrafts = false
canonifyurls = true
contentdir = "content"
postdir = "content"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true

[params]
  Author = "Michał Kowol"
  DateForm = "2006-01-02"
  Title = "Michał Kowol"
  Tagline = "Tech Blog"
  disqusShortname = "michalkowol"
  description = "<strong style=\"color: white;\">Michał Kowol</strong> | Tech Blog"

[params.Github]
  Url = "https://github.com/michalkowol"
